# Introduction {#intro}

The aging trend of the U.S. bridge inventory has been arisen by the ASCE in the recent years [@asce2017InfrastructureReport2017]. An increasing population of older bridges creates a challenging scenario for the future bridge maintenance strategy. However, the observed reduction of the structurally defficient bridges is a first step forward.

```{r bridge-age, fig.cap='Age distribution of US bridges (1992 vs. 2017)', out.width='80%', fig.asp=.75, fig.align='center', echo=FALSE, warning=FALSE, message=FALSE}

# Get age in 1992 vs. 2017
# age.1992 = 1992 - as.numeric(nbi1992$YEAR_BUILT_027) %>% as.data.frame(.)
# age.2017 = 2017 - as.numeric(nbi2017$YEAR_BUILT_027) %>% as.data.frame(.)

# save(age.1992,age.2017,file = "C:/Users/alexb/Google Drive/CVEN 6833 ADAT/zz Homeworks/temp/nbi.RData")

load("C:/Users/alexb/Google Drive/CVEN 6833 ADAT/zz Homeworks/temp/nbi.RData")

# plot.df = data.frame("1992" = age.1992, "2017" = age.2017)

ggplot(age.1992, aes(x=.)) + 
  # geom_histogram(aes(y=..density..), colour="black", fill="white",
                 # group = "1992") +
  xlim (0,150) +
  geom_density(alpha=.2, fill="#FF6666",adjust = 2) +
  # geom_histogram(data = age.2017, aes(x=., y=..density..), 
                 # colour="black", fill=NA) +
  geom_density(data = age.2017,aes(x=., y=..density..), alpha=.2, fill="blue",
               adjust = 2) +
  labs(x = "Age") +
  theme(plot.caption = element_text(hjust = 0.5,size = rel(1.1))) +
  scale_fill_manual(name="Year",values=c("#FF6666","blue"),labels=c("1992","2017"))
  
# qplot(age.1992,geom = "histogram")
```

Figure \@ref(fig:bridge-age) shows the formentioned aging effect. The data has been downloaded from the publicly accessible National Bridge Inventory (NBI) of the U.S. Federal Highway Administration. The horizontal shift between peak densities represent the time lag (26 years), while the vertical shift shows a decrease in the total population density.

Stablishing the right criteria to sustain bridge condition on safe levels is a key factor in a problem of limited resource allocation. Thus, the study of the relation between bridge characteristics and bridge performance can uncover better bridge maintenance policies.
